services:
  healthchecker:
    image: ghcr.io/braveokafor/healthchecker-py:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    volumes:
      - ./examples:/config
    environment:
      - SMTP_USERNAME=user
      - SMTP_PASSWORD=pass
      - SMTP_SERVER=mailhog
      - SMTP_PORT=1025
      - SMTP_TLS=false
    restart: unless-stopped
    command: --config /config/config.yaml
    depends_on:
      - mailhog

  # For testing email alerts locally
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
