on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
